spring:
 eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url: http://localhost:8761/eureka

 spring:
  application:
   name: Config-Default
